apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: default
  labels:
    app: helloworld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-deployment
  template:
    metadata:
      labels:
        app: helloworld-deployment
    spec:
      containers:
        - name: springapp
          image: yogeshpri/my_spring_app
          imagePullPolicy: Always
